spring:
  application:
    name: user-service

  datasource:
    url: jdbc:h2:mem:timesale;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update # 개발 환경
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: v3ry-s3cr3t-k3y-f0r-t1m3-s4l3-ec0mm3rc3-pr0j3ct
  access-token-validity-in-seconds: 3600