spring:
  application:
    name: product-service

  profiles:
    include: infrastructure

server:
  port: 8081

jwt:
  secret: v3ry-s3cr3t-k3y-f0r-t1m3-s4l3-ec0mm3rc3-pr0j3ct
  access-token-validity-in-seconds: 3600

grpc:
  server:
    port: 9090